{% set name = "dask-histogram" %}
{% set version = "2022.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dask_histogram/dask-histogram-{{ version }}.tar.gz
  sha256: 6505c5f63c5d236f4b7e8b4c2962733a73b0f8132865a117b6f0ed0fbb4f00aa

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=42
    - setuptools-scm >=3.4
    - toml
  run:
    - python >=3.8
    - dask
    - boost-histogram

test:
  requires:
    - pytest
  source_files:
    - tests
  imports:
    - dask_histogram
  commands:
    - pytest

about:
  home: https://dask-histogram.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Scale up histogramming with Dask.
  description: |
    Dask histogram extends the boost-histogram library to provide
    compatibility with Dask collections.
  doc_url: https://dask-histogram.readthedocs.io/
  dev_url: https://github.com/dask-contrib/dask-histogram/

extra:
  recipe-maintainers:
    - douglasdavis
