{% set name = "dask-histogram" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d852a59223b15736888c24b80e581e80749e4388f43436bdfbd85adf85be0f66

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools >=42
    - setuptools-scm >=3.4
    - toml
  run:
    - python >=3.7
    - dask
    - boost-histogram

test:
  requires:
    - pytest
  source_files:
    - tests
  imports:
    - dask_histogram
  commands:
    - pytest

about:
  home: https://dask-histogram.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Scale up histogramming with Dask.
  description: |
    Dask histogram extends the boost-histogram library to provide
    compatibility with Dask collections.
  doc_url: https://dask-histogram.readthedocs.io/
  dev_url: https://github.com/dask-contrib/dask-histogram/

extra:
  recipe-maintainers:
    - douglasdavis
